### ISSUE TITLE
Imagem não ocupando todo o espaço disponível

### ISSUE THREAD

**Issue by Rodolfho7** [mtsGiroto/50projects50days#1]
![barra-branca](https://user-images.githubusercontent.com/18689467/108537344-44e1d100-72bc-11eb-850d-f05773eebb68.JPG)
no css, adicione na classe **panel** a proprieda
de: **background-size: cover;**
![sem-barra-branca](https://user-images.githubusercontent.com/18689467/108537349-4612fe00-72bc-11eb-94ea-1b1cc47601e5.JPG)

**Comment by mtsGiroto** [comment]
Obrigado pela dica Rodolfho vou alterar!
